[package]
name = "demeter-daemon"
version = "0.1.0"
authors = ["Christopher MÃ¼hl <christopher@dieschittigs.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
